# Generated by Django 6.1.1 on 2026-10-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='google_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
