# Generated by Django 6.1.1 on 2026-09-21 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gmail_send', 'Send Gmail'), ('calendar_create', 'Create Calendar Event'), ('calendar_update', 'Update Calendar Event'), ('drive_folder', 'Create Drive Folder'), ('drive_save', 'Save File to Drive'), ('sheets_write', 'Write to Sheets'), ('task_create', 'Create Internal Task'), ('notify', 'Send Notification')], max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=1)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automation.automation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('contains', 'Contains'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than')], max_length=30)),
                ('value', models.CharField(max_length=255)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='automation.automation')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gmail_new', 'New Gmail Message'), ('gmail_search', 'Gmail Search Match'), ('calendar_new', 'New Calendar Event'), ('calendar_upcoming', 'Upcoming Calendar Event'), ('drive_new', 'New Drive File'), ('scheduled', 'Scheduled'), ('manual', 'Manual')], max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('automation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trigger', to='automation.automation')),
            ],
        ),
    ]
