# Generated by Django 6.1.1 on 2026-09-22 05:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_automationexecution_automationstepresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationexecution',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
