# Generated by Django 6.1.1 on 2026-10-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_automationexecution_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
