/**
 * api.ts — centralised HTTP client for the Django REST Framework backend.
 *
 * All requests are routed through `apiFetch` so the base URL lives in one
 * place (NEXT_PUBLIC_API_BASE_URL).  Auth pages import the typed helpers
 * below; nothing else should construct raw fetch calls.
 */

import type {
  LoginRequest,
  LoginResponse,
  RegisterRequest,
  RegisterResponse,
  GoogleOAuthUrlResponse,
  ApiError,
} from "@/types/auth";

// ─── Base config ────────────────────────────────────────────────────────────

const BASE_URL =
  process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/$/, "") ??
  "http://localhost:8000";

// ─── Core fetch wrapper ─────────────────────────────────────────────────────

export class ApiResponseError extends Error {
  status: number;
  data: ApiError;

  constructor(status: number, data: ApiError) {
    // Prefer a `detail` field from DRF, then fall back to HTTP status text.
    super(data.detail ?? `Request failed with status ${status}`);
    this.name = "ApiResponseError";
    this.status = status;
    this.data = data;
  }
}

async function apiFetch<T>(
  path: string,
  options: RequestInit = {}
): Promise<T> {
  const url = `${BASE_URL}${path}`;
  // Get token from localStorage if we are in the browser
  const token = typeof window !== "undefined" ? localStorage.getItem("access_token") : null;
  const authHeader = token ? { Authorization: `Bearer ${token}` } : {};

  const res = await fetch(url, {
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
      ...authHeader,
      ...(options.headers ?? {}),
    },
    ...options,
  });

  // Parse JSON even on error responses — DRF always returns JSON bodies.
  let data: unknown;
  try {
    data = await res.json();
  } catch {
    data = {};
  }

  if (!res.ok) {
    throw new ApiResponseError(res.status, data as ApiError);
  }

  return data as T;
}

// ─── Auth endpoints ──────────────────────────────────────────────────────────

/**
 * POST /api/auth/login/
 * Authenticates a user with email + password.
 * Returns access/refresh tokens and the user object.
 */
export async function login(payload: LoginRequest): Promise<LoginResponse> {
  return apiFetch<LoginResponse>("/api/auth/login/", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

/**
 * POST /api/auth/register/
 * Creates a new user account.
 * Returns access/refresh tokens and the newly created user object.
 */
export async function register(
  payload: RegisterRequest
): Promise<RegisterResponse> {
  return apiFetch<RegisterResponse>("/api/auth/register/", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

/**
 * GET /api/auth/google/
 * Returns the Google OAuth URL generated by the backend.
 * The frontend simply redirects the browser to `auth_url`.
 * No OAuth logic is implemented here.
 */
export async function getGoogleOAuthUrl(): Promise<GoogleOAuthUrlResponse> {
  return apiFetch<GoogleOAuthUrlResponse>("/api/auth/google/");
}

// ─── Error helpers ───────────────────────────────────────────────────────────

/**
 * Extracts a human-readable error message from an ApiResponseError or a
 * plain Error.  Handles DRF field-level validation errors by joining them.
 */
export function extractErrorMessage(err: unknown): string {
  if (err instanceof ApiResponseError) {
    const { data } = err;

    // Field-level errors (e.g. { email: ["Enter a valid email."] })
    const fieldErrors = Object.entries(data)
      .filter(([key]) => key !== "detail")
      .flatMap(([, msgs]) => (Array.isArray(msgs) ? msgs : [msgs]))
      .filter(Boolean)
      .join(" ");

    if (fieldErrors) return fieldErrors;

    // Top-level detail
    if (data.detail) return data.detail;
  }

  if (err instanceof Error) return err.message;

  return "An unexpected error occurred. Please try again.";
}
