/**
 * api.ts — centralised HTTP client for the Django REST Framework backend.
 *
 * All requests are routed through `apiFetch` so the base URL lives in one
 * place. Auth, Gmail, and Notifications helpers are exposed below.
 */

import type {
  LoginRequest,
  LoginResponse,
  RegisterRequest,
  RegisterResponse,
  GoogleOAuthUrlResponse,
  ApiError,
} from "../types/auth";

import type {
  GmailComposeRequest,
  GmailDraftResponse,
  GmailListParams,
  GmailMessage,
  GmailMessageListResponse,
  GmailSearchParams,
  GmailSendResponse,
} from "../types/gmail";

import type {
  NotificationListResponse,
  NotificationMarkAllReadResponse,
  NotificationReadResponse,
} from "../types/notifications";

// ─── Base config ─────────────────────────────────────────────────────────────

const BASE_URL =
  process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/$/, "") ??
  "http://localhost:8000";

// ─── Error class ──────────────────────────────────────────────────────────────

export class ApiResponseError extends Error {
  status: number;
  data: ApiError;

  constructor(status: number, data: ApiError) {
    super(data.detail ?? `Request failed with status ${status}`);
    this.name = "ApiResponseError";
    this.status = status;
    this.data = data;
  }
}

// ─── Core fetch wrapper ───────────────────────────────────────────────────────

async function apiFetch<T>(
  path: string,
  options: RequestInit = {}
): Promise<T> {
  const url = `${BASE_URL}${path}`;

  const token =
    typeof window !== "undefined"
      ? localStorage.getItem("access_token")
      : null;

  /*
   * Use the Headers API instead of spreading options.headers.
   *
   * RequestInit.headers can be Headers, an array, or an object.
   * new Headers() safely handles all of those forms.
   */
  const headers = new Headers(options.headers);

  if (!headers.has("Content-Type")) {
    headers.set("Content-Type", "application/json");
  }

  if (!headers.has("Accept")) {
    headers.set("Accept", "application/json");
  }

  if (token) {
    headers.set("Authorization", `Bearer ${token}`);
  }

  const res = await fetch(url, {
    ...options,
    headers,
  });

  // Parse JSON even on error responses.
  let data: unknown;

  try {
    data = await res.json();
  } catch {
    data = {};
  }

  if (!res.ok) {
    throw new ApiResponseError(res.status, data as ApiError);
  }

  return data as T;
}

// ─── Auth endpoints ──────────────────────────────────────────────────────────

/**
 * POST /api/auth/login/
 *
 * Authenticates a user with email + password.
 * Returns access/refresh tokens and the user object.
 */
export async function login(
  payload: LoginRequest
): Promise<LoginResponse> {
  return apiFetch<LoginResponse>("/api/auth/login/", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

/**
 * POST /api/auth/register/
 *
 * Creates a new user account.
 * Returns access/refresh tokens and the newly created user object.
 */
export async function register(
  payload: RegisterRequest
): Promise<RegisterResponse> {
  return apiFetch<RegisterResponse>("/api/auth/register/", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

/**
 * GET /api/auth/google/
 *
 * Returns the Google OAuth URL generated by the backend.
 * The frontend redirects the browser to that URL.
 */
export async function getGoogleOAuthUrl(): Promise<GoogleOAuthUrlResponse> {
  return apiFetch<GoogleOAuthUrlResponse>("/api/auth/google/");
}

// ─── Error helpers ───────────────────────────────────────────────────────────

/**
 * Extracts a human-readable error message from an ApiResponseError
 * or a plain Error.
 */
export function extractErrorMessage(err: unknown): string {
  if (err instanceof ApiResponseError) {
    const { data } = err;

    // Field-level errors:
    // { email: ["Enter a valid email."] }
    const fieldErrors = Object.entries(data)
      .filter(([key]) => key !== "detail")
      .flatMap(([, messages]) =>
        Array.isArray(messages) ? messages : [messages]
      )
      .filter(Boolean)
      .join(" ");

    if (fieldErrors) {
      return fieldErrors;
    }

    if (data.detail) {
      return data.detail;
    }
  }

  if (err instanceof Error) {
    return err.message;
  }

  return "An unexpected error occurred. Please try again.";
}

// ─── Gmail endpoints ─────────────────────────────────────────────────────────

/**
 * GET /api/gmail/messages/
 *
 * Returns the inbox message list for the authenticated user.
 */
export async function listGmailMessages(
  params: GmailListParams = {}
): Promise<GmailMessageListResponse> {
  const query = new URLSearchParams();

  if (params.max_results) {
    query.set("max_results", String(params.max_results));
  }

  if (params.page_token) {
    query.set("page_token", params.page_token);
  }

  const qs = query.toString() ? `?${query.toString()}` : "";

  return apiFetch<GmailMessageListResponse>(
    `/api/gmail/messages/${qs}`
  );
}

/**
 * GET /api/gmail/messages/<id>/
 *
 * Returns a single Gmail message in full format.
 */
export async function getGmailMessage(
  messageId: string
): Promise<GmailMessage> {
  return apiFetch<GmailMessage>(
    `/api/gmail/messages/${messageId}/`
  );
}

/**
 * GET /api/gmail/search/?q=<query>
 *
 * Searches Gmail messages using Gmail query syntax.
 */
export async function searchGmailMessages(
  params: GmailSearchParams
): Promise<GmailMessageListResponse> {
  const query = new URLSearchParams({
    q: params.q,
  });

  if (params.max_results) {
    query.set("max_results", String(params.max_results));
  }

  if (params.page_token) {
    query.set("page_token", params.page_token);
  }

  return apiFetch<GmailMessageListResponse>(
    `/api/gmail/search/?${query.toString()}`
  );
}

/**
 * POST /api/gmail/send/
 *
 * Sends an email on behalf of the authenticated user.
 *
 * NOTE:
 * Requires gmail.send scope.
 * The current OAuth configuration only grants gmail.readonly.
 */
export async function sendGmailMessage(
  payload: GmailComposeRequest
): Promise<GmailSendResponse> {
  return apiFetch<GmailSendResponse>("/api/gmail/send/", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

/**
 * POST /api/gmail/drafts/
 *
 * Creates a Gmail draft on behalf of the authenticated user.
 *
 * NOTE:
 * Requires a write-capable Gmail OAuth scope.
 */
export async function createGmailDraft(
  payload: GmailComposeRequest
): Promise<GmailDraftResponse> {
  return apiFetch<GmailDraftResponse>("/api/gmail/drafts/", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

/**
 * GET /api/gmail/attachments/<messageId>/<attachmentId>/
 *
 * Downloads a Gmail attachment as a Blob.
 */
export async function downloadGmailAttachment(
  messageId: string,
  attachmentId: string
): Promise<Blob> {
  const url =
    `${BASE_URL}/api/gmail/attachments/` +
    `${messageId}/${attachmentId}/`;

  const token =
    typeof window !== "undefined"
      ? localStorage.getItem("access_token")
      : null;

  const headers = new Headers();

  if (token) {
    headers.set("Authorization", `Bearer ${token}`);
  }

  const res = await fetch(url, {
    method: "GET",
    headers,
  });

  if (!res.ok) {
    let data: unknown = {};

    try {
      data = await res.json();
    } catch {
      // Response may be binary.
    }

    throw new ApiResponseError(
      res.status,
      data as ApiError
    );
  }

  return res.blob();
}

// ─── Notifications endpoints ────────────────────────────────────────────────

/**
 * GET /api/notifications/
 *
 * Returns notifications for the authenticated user.
 *
 * Pass unread_only=true to receive only unread notifications.
 */
export async function listNotifications(
  unreadOnly = false
): Promise<NotificationListResponse> {
  const qs = unreadOnly ? "?unread_only=true" : "";

  return apiFetch<NotificationListResponse>(
    `/api/notifications/${qs}`
  );
}

/**
 * PATCH /api/notifications/<id>/read/
 *
 * Marks a single notification as read.
 */
export async function markNotificationRead(
  notificationId: number
): Promise<NotificationReadResponse> {
  return apiFetch<NotificationReadResponse>(
    `/api/notifications/${notificationId}/read/`,
    {
      method: "PATCH",
    }
  );
}

/**
 * POST /api/notifications/read-all/
 *
 * Marks every unread notification as read.
 */
export async function markAllNotificationsRead(): Promise<NotificationMarkAllReadResponse> {
  return apiFetch<NotificationMarkAllReadResponse>(
    "/api/notifications/read-all/",
    {
      method: "POST",
    }
  );
}